apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
spec:
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 16
          type: Pods
          value: 5
        - periodSeconds: 16
          type: Percent
          value: 99
      selectPolicy: Max
      stabilizationWindowSeconds: 60
    scaleUp:
      policies:
        - periodSeconds: 16
          type: Pods
          value: 5
        - periodSeconds: 16
          type: Percent
          value: 100
      selectPolicy: Max
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # scale up if usage is above
        # 99% of the requested CPU (100m)
        averageUtilization: 99
